### ISSUE TITLE
VerifyAddUserについて

### ISSUE THREAD

**Issue by segnities007** [onion0904/segon_pix#92]
これは仕様(というか無視していいやつ)？

api-1  | 2024/11/02 05:20:48 /app/repositories/auth.go:15 record not found
api-1  | [13.430ms] [rows:0] SELECT * FROM `users` WHERE email = 'user@example.com' AND `users`.`deleted_at` IS NULL ORDER BY `users`.`id` LIMIT 1
api-1  | Email is user@example.com
api-1  | 2024/11/02 05:20:48 Failed to bind request data: code=400, message=EOF, internal=EOF
api-1  | {"time":"2024-11-02T05:20:48.027753219Z","id":"","remote_ip":"172.17.0.1","host":"localhost:8080","method":"POST","uri":"/verify?code=oOPyl0go","user_agent":"curl/8.10.1","status":200,"error":"","latency":14482038,"latency_human":"14.482038ms","bytes_in":101,"bytes_out":235}

**Comment by onion0904** [comment]
すでにユーザーが存在するか確認するためのものです。そのエラーが出た場合、指定されたユーザーが存在しないことになるので正常にユーザーを作成できると思います。ログイン時にこのエラーが出た場合は逆に正常ではないという解釈になります。

**Comment by segnities007** [comment]
ありがとうございます
